#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d                

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer false
bspc config focus_by_distance false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color '#1d2021'
bspc config focused_border_color '#ddc7a1'
bspc config presel_border_color '#FFDB91'
bspc config normal_sticky_border_color '#282A2E'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color '#F28B82'

exec nitrogen --restore &
exec picom &
$HOME/.config/polybar/launch.sh &
dunst
